//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneracionNumeracionAvalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneracionNumeracionAvalonia.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Separados por comas | *.csv.
        /// </summary>
        public static string ArchivoCSV {
            get {
                return ResourceManager.GetString("ArchivoCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo excel (*.xlsx) | *.xlsx.
        /// </summary>
        public static string ArchivoExcel {
            get {
                return ResourceManager.GetString("ArchivoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2024 | Artes Gráficas Díaz-Hellín.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre de registros y numeradores\n ¿Desea Continuar?..
        /// </summary>
        public static string DescuadreRegistroNumeradores {
            get {
                return ResourceManager.GetString("DescuadreRegistroNumeradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro Fin no puede ser menor 0..
        /// </summary>
        public static string ErrorFinMenor0 {
            get {
                return ResourceManager.GetString("ErrorFinMenor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro Fin no puede ser menor o igual que el de Inicio..
        /// </summary>
        public static string ErrorFinMenorInicio {
            get {
                return ResourceManager.GetString("ErrorFinMenorInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error..
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los numeradores no pueden ser menor o igual a 0..
        /// </summary>
        public static string ErrorNumeradores0 {
            get {
                return ResourceManager.GetString("ErrorNumeradores0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al obtener la ruta..
        /// </summary>
        public static string ErrorRuta {
            get {
                return ResourceManager.GetString("ErrorRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin: .
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato: .
        /// </summary>
        public static string Formato {
            get {
                return ResourceManager.GetString("Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generador de Base de Datos.
        /// </summary>
        public static string GeneradorBaseDatos {
            get {
                return ResourceManager.GetString("GeneradorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        public static string Generar {
            get {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha guardado correctamente..
        /// </summary>
        public static string GuardadoCorrectamente {
            get {
                return ResourceManager.GetString("GuardadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio: .
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerador .
        /// </summary>
        public static string Numerador {
            get {
                return ResourceManager.GetString("Numerador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerador del.
        /// </summary>
        public static string NumeradorDel {
            get {
                return ResourceManager.GetString("NumeradorDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeradores del.
        /// </summary>
        public static string NumeradoresDel {
            get {
                return ResourceManager.GetString("NumeradoresDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de numeradores: .
        /// </summary>
        public static string NumeroNumeradores {
            get {
                return ResourceManager.GetString("NumeroNumeradores", resourceCulture);
            }
        }
    }
}
