name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GeneracionNumeracionAvalonia.sln

      - name: Build
        run: dotnet build GeneracionNumeracionAvalonia.sln

      - name: Test
        continue-on-error: false  
        run: dotnet test GeneracionNumeracionTest/GeneracionNumeracionTest.csproj

      - name: Package
        run: |
          sh package/Macos/packaging.sh 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeneracionNumeracion.pkg
          path: ${{ github.workspace }}/GeneracionNumeracion-*.pkg

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GeneracionNumeracionAvalonia.sln

      - name: Build
        run: dotnet build GeneracionNumeracionAvalonia.sln

      - name: Test
        continue-on-error: false  
        run: dotnet test GeneracionNumeracionTest/GeneracionNumeracionTest.csproj

      - name: Package
        run: dotnet publish GeneracionNumeracionAvalonia/GeneracionNumeracionAvalonia.csproj -c Release -f net8.0 -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true /p:GenerateAppxPackageOnBuild=true

      - name: Rename file with short commit hash
        shell: bash
        run: |
          HASH=$(git rev-parse --short HEAD)
          echo "Short commit hash: ${HASH}"
          mv GeneracionNumeracionAvalonia/bin/Release/net8.0/win-x64/publish/*.exe GeneracionNumeracionAvalonia/bin/Release/net8.0/win-x64/publish/GeneracionNumeracion-${HASH}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeneracionNumeracion.exe
          path: GeneracionNumeracionAvalonia/bin/Release/net8.0/win-x64/publish/GeneracionNumeracion-*.exe


  cleanup-macos:
    runs-on: macos-latest
    needs: [macos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean workspace for macOS
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

  cleanup-windows:
    runs-on: windows-latest
    needs: [windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean workspace for Windows
        run: |
          Remove-Item -Path *.* -Force -Recurse